NUMPY

In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr.shape

(5,)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2.shape

(2, 3)

In [7]:
arr2[0]                    #grabbing row        arr2[row_index]

array([1, 2, 3])

In [8]:
arr2[0][0]                  #grabbing element   arr2[row_no,column_no]

1

In [9]:
arr2[:,1]                   #grabbing columns    arr2[:,column_index]

array([2, 5])

In [10]:
arr2[0:,:1]                

array([[1],
       [4]])

In [11]:
arr2[0:,:2]                 #selecting submatrix   arr2[start_index:end_index,start_index:end_index]

array([[1, 2],
       [4, 5]])

In [12]:
arr2[:,2]

array([3, 6])

In [13]:
arr = np.arange(1,11)       #arranging elements   arr=np.arange(beg_no,end_no+1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.arange(0,21,2)     #arranging elements with step size
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
arr = np.arange(50).reshape(5,10)     #creating a 1D array and converting it into a matrix
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
arr[1:3]                    #slicing rows

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
arr[1:3,3:5]                #slicing rows and columns

array([[13, 14],
       [23, 24]])

operations on array


In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [23]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [24]:
np.zeros(10)               #creating array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)                #creating array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.random.rand(1)          #to generate a random number between -1 and 1

array([0.62091028])

In [35]:
np.random.randn(2,3)

array([[-0.09511716,  0.31658451, -1.04337227],
       [ 0.67716854, -0.94765851,  0.09794965]])

In [27]:
np.linspace(0,1,20)        #to create array of N(=20)linearly spaaced numbers between 0 and 1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [29]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array(lst1)
arr2 = np.array([lst1,lst2,lst3])   #multinested array
print("arr1 ="+str(arr1))
print("arr2 ="+str(arr2))

arr1 =[1 2 3 4 5]
arr2 =[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [30]:
arr1[3:]=0
arr1

array([1, 2, 3, 0, 0])

In [32]:
arr1[arr1<3]     #conditional

array([1, 2, 0, 0])

In [36]:
np.random.randint(0,100,5)      #np.random.randint(beg_no,end_no,no_of_values) this returns array of integers

array([38, 72, 71, 26, 14])

In [40]:
np.random.random_sample((2,5))      #array of nos. between 0 and 1

array([[0.8487866 , 0.60987026, 0.02354049, 0.82857343, 0.21073695],
       [0.59691959, 0.29636042, 0.73142796, 0.5974832 , 0.15252937]])